var searchData=
[
  ['a_20folder_0',['Generate Documentation for a Folder',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2doc__commands.html#autotoc_md74',1,'']]],
  ['a_20jira_20api_20token_1',['Creating a JIRA API Token',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2config-commands.html#autotoc_md33',1,'']]],
  ['a_20specific_20file_2',['Generate Documentation for a Specific File',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2doc__commands.html#autotoc_md73',1,'']]],
  ['add_5fcomment_3',['add_comment',['../classpenify__hook_1_1jira__client_1_1JiraClient.html#aa1f374116c64cd5f1492ec7f7e40f9c1',1,'penify_hook::jira_client::JiraClient']]],
  ['additional_20resources_4',['Additional Resources',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2penify-cli-documentation.html#autotoc_md155',1,'']]],
  ['advanced_20commands_20login_20required_5',['Advanced Commands (Login required)',['..//app/doc_state/github_reposRepoArchDocGenContext/Penify-dev/penify-cli/README.md#autotoc_md163',1,'']]],
  ['advanced_20hook_20scenarios_6',['Advanced Hook Scenarios',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2doc__commands.html#autotoc_md88',1,'']]],
  ['advanced_20use_20cases_7',['Advanced Use Cases',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2detailed-usage.html#autotoc_md56',1,'Advanced Use Cases'],['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2doc__commands.html#autotoc_md94',1,'Advanced Use Cases']]],
  ['ai_8',['Workflow 1: Efficient Git Commits with AI',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2example-workflows.html#autotoc_md104',1,'']]],
  ['all_20features_9',['Full Workflow with All Features',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2commit-commands.html#autotoc_md17',1,'']]],
  ['and_20description_20with_20context_10',['Generate Title and Description with Context',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2commit-commands.html#autotoc_md8',1,'']]],
  ['and_20edit_20full_20commit_20message_11',['Generate and Edit Full Commit Message',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2commit-commands.html#autotoc_md9',1,'']]],
  ['and_20jira_20integration_12',['LLM and JIRA Integration',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2commit-commands.html#autotoc_md11',1,'']]],
  ['and_20provide_20context_13',['Generate, Edit, and Provide Context',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2commit-commands.html#autotoc_md10',1,'']]],
  ['anthropic_14',['Anthropic',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2config-commands.html#autotoc_md27',1,'']]],
  ['api_20token_15',['Creating a JIRA API Token',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2config-commands.html#autotoc_md33',1,'']]],
  ['api_20token_20storage_16',['API Token Storage',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2detailed-usage.html#autotoc_md45',1,'']]],
  ['api_5fclient_17',['api_client',['../classpenify__hook_1_1base__analyzer_1_1BaseAnalyzer.html#a81e9c55709205aaf4ebbe2b41683baf2',1,'penify_hook::base_analyzer::BaseAnalyzer']]],
  ['api_5fclient_2epy_18',['api_client.py',['../api__client_8py.html',1,'']]],
  ['api_5furl_19',['API_URL',['../namespacepenify__hook_1_1constants.html#a846767f047a1319005bc95395330ab34',1,'penify_hook::constants']]],
  ['api_5furl_20',['api_url',['../classpenify__hook_1_1api__client_1_1APIClient.html#a130cf688ed35dc0e8cbd8320b6b2d872',1,'penify_hook::api_client::APIClient']]],
  ['apiclient_21',['APIClient',['../classpenify__hook_1_1api__client_1_1APIClient.html',1,'penify_hook::api_client']]],
  ['auth_5fcommands_2epy_22',['auth_commands.py',['../auth__commands_8py.html',1,'']]],
  ['auth_5ftoken_23',['AUTH_TOKEN',['../classpenify__hook_1_1api__client_1_1APIClient.html#a5bb502603717946ad710b49ad9d95237',1,'penify_hook::api_client::APIClient']]],
  ['authentication_24',['Authentication',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2detailed-usage.html#autotoc_md43',1,'Authentication'],['..//app/doc_state/github_reposRepoArchDocGenContext/Penify-dev/penify-cli/README.md#autotoc_md167',1,'Authentication']]],
  ['authentication_20requirement_25',['Authentication Requirement',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2detailed-usage.html#autotoc_md51',1,'']]],
  ['author_26',['Author',['..//app/doc_state/github_reposRepoArchDocGenContext/Penify-dev/penify-cli/README.md#autotoc_md173',1,'']]],
  ['author_27',['author',['../namespacesetup.html#a3a57a4772d418a06835249cbade0d86a',1,'setup']]],
  ['author_3a_20suman_20sauarbh_28',['author: Suman Sauarbh',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2penify-cli-documentation.html#autotoc_md124',1,'']]],
  ['author_5femail_29',['author_email',['../namespacesetup.html#a5b08034343aa2be607722a8b315f3625',1,'setup']]],
  ['autoreset_30',['autoreset',['../namespacepenify__hook_1_1ui__utils.html#ab560cfade398ac1e0bd47befb52d9f71',1,'penify_hook::ui_utils']]],
  ['azure_20openai_31',['Azure OpenAI',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2config-commands.html#autotoc_md29',1,'']]]
];
