var searchData=
[
  ['ui_5futils_2epy_0',['ui_utils.py',['../ui__utils_8py.html',1,'']]],
  ['understanding_1',['Workflow 5: Legacy Code Understanding',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2example-workflows.html#autotoc_md121',1,'']]],
  ['uninstall_20hook_20from_20current_20repository_2',['Uninstall Hook from Current Repository',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2doc__commands.html#autotoc_md77',1,'']]],
  ['uninstall_20hook_20from_20specific_20repository_3',['Uninstall Hook from Specific Repository',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2doc__commands.html#autotoc_md78',1,'']]],
  ['uninstall_20hook_20tt_4',['&lt;tt&gt;uninstall-hook&lt;/tt&gt;',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2doc__commands.html#autotoc_md70',1,'']]],
  ['uninstall_5fgit_5fhook_5',['uninstall_git_hook',['../namespacepenify__hook_1_1commands_1_1hook__commands.html#a1b2b3ffff51d19300a0b7ea785678443',1,'penify_hook::commands::hook_commands']]],
  ['uninstallation_6',['Uninstallation',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2doc__commands.html#autotoc_md89',1,'Hook Uninstallation'],['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2doc__commands.html#autotoc_md91',1,'Specific Repository Uninstallation'],['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2doc__commands.html#autotoc_md90',1,'Standard Uninstallation'],['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2doc__commands.html#autotoc_md93',1,'Verifying Uninstallation']]],
  ['update_5fissue_5fstatus_7',['update_issue_status',['../classpenify__hook_1_1jira__client_1_1JiraClient.html#aca8837552d37bfd611de23441a240826',1,'penify_hook::jira_client::JiraClient']]],
  ['update_5fstage_8',['update_stage',['../namespacepenify__hook_1_1ui__utils.html#ad8be9c5a2708c211a651e2b3dfb54bcd',1,'penify_hook::ui_utils']]],
  ['url_9',['url',['../namespacesetup.html#afc13124aa5c0124e84e1d965e3f4b0fb',1,'setup']]],
  ['usage_10',['Usage',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2commit-commands.html#autotoc_md1',1,'Basic Usage'],['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2config-commands.html#autotoc_md22',1,'Basic Usage'],['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2doc__commands.html#autotoc_md65',1,'Basic Usage'],['..//app/doc_state/github_reposRepoArchDocGenContext/Penify-dev/penify-cli/README.md#autotoc_md159',1,'Usage']]],
  ['usage_20guide_11',['Penify CLI - Detailed Usage Guide',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2detailed-usage.html',1,'']]],
  ['usage_3a_12',['Usage:',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2penify-cli-documentation.html#autotoc_md131',1,'Usage:'],['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2penify-cli-documentation.html#autotoc_md137',1,'Usage:'],['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2penify-cli-documentation.html#autotoc_md142',1,'Usage:'],['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2penify-cli-documentation.html#autotoc_md147',1,'Usage:']]],
  ['use_20cases_13',['Use Cases',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2detailed-usage.html#autotoc_md56',1,'Advanced Use Cases'],['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2doc__commands.html#autotoc_md94',1,'Advanced Use Cases'],['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2detailed-usage.html#autotoc_md50',1,'Use Cases']]],
  ['using_20local_20llm_14',['Using Local LLM',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2commit-commands.html#autotoc_md12',1,'']]],
  ['utils_2epy_15',['utils.py',['../utils_8py.html',1,'']]]
];
