var searchData=
[
  ['d_20description_20tt_0',['&lt;tt&gt;-d, --description&lt;/tt&gt;',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2commit-commands.html#autotoc_md5',1,'']]],
  ['daily_20workflow_1',['Daily Workflow',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2example-workflows.html#autotoc_md106',1,'Daily Workflow'],['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2example-workflows.html#autotoc_md110',1,'Daily Workflow']]],
  ['dashboard_5furl_2',['DASHBOARD_URL',['../namespacepenify__hook_1_1constants.html#ae4a03ab3b19d60436c72484b313079c8',1,'penify_hook::constants']]],
  ['debugging_3',['Debugging',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2doc__commands.html#autotoc_md101',1,'']]],
  ['default_20settings_4',['Basic Commit with Default Settings',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2commit-commands.html#autotoc_md16',1,'']]],
  ['description_5',['description',['../namespacesetup.html#aedf461ec52a946bda975938ba0b93ec0',1,'setup']]],
  ['description_20tt_6',['&lt;tt&gt;-d, --description&lt;/tt&gt;',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2commit-commands.html#autotoc_md5',1,'']]],
  ['description_20with_20context_7',['Generate Title and Description with Context',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2commit-commands.html#autotoc_md8',1,'']]],
  ['detailed_20command_20documentation_8',['Detailed Command Documentation',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2penify-cli-documentation.html#autotoc_md129',1,'']]],
  ['detailed_20usage_20guide_9',['Penify CLI - Detailed Usage Guide',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2detailed-usage.html',1,'']]],
  ['detailed_2dusage_2emd_10',['detailed-usage.md',['../detailed-usage_8md.html',1,'']]],
  ['development_11',['Development',['..//app/doc_state/github_reposRepoArchDocGenContext/Penify-dev/penify-cli/README.md#autotoc_md170',1,'']]],
  ['diff_12',['Generate Documentation for Current Git Diff',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2doc__commands.html#autotoc_md72',1,'']]],
  ['dir_5fpath_13',['dir_path',['../classpenify__hook_1_1folder__analyzer_1_1FolderAnalyzerGenHook.html#a53f73d69cc0f00763ee4830e4f0f7393',1,'penify_hook::folder_analyzer::FolderAnalyzerGenHook']]],
  ['doc_5fcommands_2emd_14',['doc_commands.md',['../doc__commands_8md.html',1,'']]],
  ['doc_5fcommands_2epy_15',['doc_commands.py',['../doc__commands_8py.html',1,'']]],
  ['docgen_20command_16',['Docgen Command',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2penify-cli-documentation.html#autotoc_md146',1,'']]],
  ['docgen_5fdescription_17',['docgen_description',['../namespacepenify__hook_1_1commands_1_1doc__commands.html#a6dd45546559198f9f79caccd030d3588',1,'penify_hook::commands::doc_commands']]],
  ['documentation_18',['Documentation',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2doc__commands.html#autotoc_md96',1,'Batch Documentation'],['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2penify-cli-documentation.html#autotoc_md129',1,'Detailed Command Documentation'],['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2example-workflows.html#autotoc_md111',1,'Manual Documentation'],['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2penify-cli-documentation.html#autotoc_md125',1,'Penify CLI Documentation'],['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2detailed-usage.html#autotoc_md58',1,'Remote Repository Documentation']]],
  ['documentation_19',['penify-cli-documentation',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2penify-cli-documentation.html',1,'']]],
  ['documentation_20for_20a_20folder_20',['Generate Documentation for a Folder',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2doc__commands.html#autotoc_md74',1,'']]],
  ['documentation_20for_20a_20specific_20file_21',['Generate Documentation for a Specific File',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2doc__commands.html#autotoc_md73',1,'']]],
  ['documentation_20for_20current_20git_20diff_22',['Generate Documentation for Current Git Diff',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2doc__commands.html#autotoc_md72',1,'']]],
  ['documentation_20generation_23',['Documentation Generation',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2detailed-usage.html#autotoc_md49',1,'Code Documentation Generation'],['..//app/doc_state/github_reposRepoArchDocGenContext/Penify-dev/penify-cli/README.md#autotoc_md165',1,'Documentation Generation']]],
  ['documentation_20generation_20commands_24',['Penify CLI - Documentation Generation Commands',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2doc__commands.html',1,'']]],
  ['documentation_20generation_20pipeline_25',['Workflow 2: Documentation Generation Pipeline',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2example-workflows.html#autotoc_md108',1,'']]],
  ['documenting_20release_20tags_26',['Documenting Release Tags',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2doc__commands.html#autotoc_md98',1,'']]],
  ['dotenv_5favailable_27',['DOTENV_AVAILABLE',['../namespacepenify__hook_1_1commands_1_1config__commands.html#a152642ab83cf6219b604bda6122aba67',1,'penify_hook::commands::config_commands']]]
];
