var searchData=
[
  ['handle_5fcommit_0',['handle_commit',['../namespacepenify__hook_1_1commands_1_1commit__commands.html#a7a856c3961f5f8914e58485644572076',1,'penify_hook::commands::commit_commands']]],
  ['handle_5fconfig_1',['handle_config',['../namespacepenify__hook_1_1config__command.html#aed769bb2e478b09003696b616edd04c5',1,'penify_hook::config_command']]],
  ['handle_5fdocgen_2',['handle_docgen',['../namespacepenify__hook_1_1commands_1_1doc__commands.html#a41d631e51b0533b7d8dc780eea52e1cc',1,'penify_hook::commands::doc_commands']]],
  ['handle_5flogin_3',['handle_login',['../namespacepenify__hook_1_1login__command.html#a13cdb8c8488b958ce536660a27521411',1,'penify_hook::login_command']]],
  ['happens_3a_4',['What happens:',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2penify-cli-documentation.html#autotoc_md143',1,'']]],
  ['help_5',['Getting Help',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2doc__commands.html#autotoc_md102',1,'']]],
  ['highlight_5fcolor_6',['HIGHLIGHT_COLOR',['../namespacepenify__hook_1_1ui__utils.html#aba01b8259f0d66cdc2b4a1b58f9736fc',1,'penify_hook::ui_utils']]],
  ['hook_7',['Post-Commit Hook',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2detailed-usage.html#autotoc_md54',1,'']]],
  ['hook_20behavior_8',['Modifying Hook Behavior',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2doc__commands.html#autotoc_md87',1,'']]],
  ['hook_20commands_9',['Git Hook Commands',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2doc__commands.html#autotoc_md79',1,'']]],
  ['hook_20customization_10',['Hook Customization',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2doc__commands.html#autotoc_md86',1,'']]],
  ['hook_20from_20current_20repository_11',['Uninstall Hook from Current Repository',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2doc__commands.html#autotoc_md77',1,'']]],
  ['hook_20from_20specific_20repository_12',['Uninstall Hook from Specific Repository',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2doc__commands.html#autotoc_md78',1,'']]],
  ['hook_20in_20current_20repository_13',['Install Hook in Current Repository',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2doc__commands.html#autotoc_md75',1,'']]],
  ['hook_20in_20specific_20repository_14',['Install Hook in Specific Repository',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2doc__commands.html#autotoc_md76',1,'']]],
  ['hook_20installation_15',['Hook Installation',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2doc__commands.html#autotoc_md80',1,'']]],
  ['hook_20integration_16',['Custom Git Hook Integration',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2doc__commands.html#autotoc_md97',1,'']]],
  ['hook_20location_17',['Custom Hook Location',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2detailed-usage.html#autotoc_md55',1,'']]],
  ['hook_20management_18',['Git Hook Management',['..//app/doc_state/github_reposRepoArchDocGenContext/Penify-dev/penify-cli/README.md#autotoc_md166',1,'']]],
  ['hook_20removal_19',['Manual Hook Removal',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2doc__commands.html#autotoc_md92',1,'']]],
  ['hook_20scenarios_20',['Advanced Hook Scenarios',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2doc__commands.html#autotoc_md88',1,'']]],
  ['hook_20script_20content_21',['Hook Script Content',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2doc__commands.html#autotoc_md82',1,'']]],
  ['hook_20tt_22',['hook tt',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2doc__commands.html#autotoc_md69',1,'&lt;tt&gt;install-hook&lt;/tt&gt;'],['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2doc__commands.html#autotoc_md70',1,'&lt;tt&gt;uninstall-hook&lt;/tt&gt;']]],
  ['hook_20uninstallation_23',['Hook Uninstallation',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2doc__commands.html#autotoc_md89',1,'']]],
  ['hook_5fcommands_2epy_24',['hook_commands.py',['../hook__commands_8py.html',1,'']]],
  ['hook_5ffilename_25',['HOOK_FILENAME',['../namespacepenify__hook_1_1commands_1_1hook__commands.html#a978b976442fbf28c29c8d0f889bfae9c',1,'penify_hook::commands::hook_commands']]],
  ['hook_5ftemplate_26',['HOOK_TEMPLATE',['../namespacepenify__hook_1_1commands_1_1hook__commands.html#a51fc390518d967f2a1e21280d7ea781b',1,'penify_hook::commands::hook_commands']]],
  ['hooks_27',['Git Hooks',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2detailed-usage.html#autotoc_md53',1,'']]],
  ['hooks_20work_28',['How Hooks Work',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2doc__commands.html#autotoc_md81',1,'']]],
  ['how_20hooks_20work_29',['How Hooks Work',['../md__2app_2doc__state_2github__reposRepoArchDocGenContext_2Penify-dev_2penify-cli_2docs_2doc__commands.html#autotoc_md81',1,'']]]
];
