penify_hook::jira_client::JiraClient
penify_hook.jira_client.JiraClient::jira_url
penify_hook.jira_client.JiraClient::jira_user
penify_hook.jira_client.JiraClient::jira_api_token
penify_hook.jira_client.JiraClient::jira_client
Referenced by penify_hook.jira_client.JiraClient.add_comment, penify_hook.jira_client.JiraClient.get_detailed_issue_context, penify_hook.jira_client.JiraClient.get_issue_details, penify_hook.commit_analyzer.CommitDocGenHook.get_summary, penify_hook.jira_client.JiraClient.is_connected, penify_hook.commit_analyzer.CommitDocGenHook.process_jira_integration, penify_hook.commit_analyzer.CommitDocGenHook.run, penify_hook.jira_client.JiraClient.update_issue_status.
def penify_hook.jira_client.JiraClient.__init__(self, str jira_url=None, str jira_user=None, str jira_api_token=None)
Initialize the JIRA client. Args: jira_url: Base URL for JIRA instance (e.g., "https://your-domain.atlassian.net") jira_user: JIRA username or email jira_api_token: JIRA API token
bool penify_hook.jira_client.JiraClient.is_connected(self)
Check if the JIRA client is connected. This function verifies whether the JIRA client has successfully established a connection. It returns `True` if the client is connected, and `False` otherwise. Returns: bool: True if the JIRA client is connected, False otherwise
References penify_hook.jira_client.JiraClient.jira_client.
Referenced by penify_hook.jira_client.JiraClient.add_comment, penify_hook.jira_client.JiraClient.enhance_commit_message, penify_hook.jira_client.JiraClient.format_commit_message_with_jira_info, penify_hook.jira_client.JiraClient.get_commit_context_from_issues, penify_hook.jira_client.JiraClient.get_detailed_issue_context, penify_hook.jira_client.JiraClient.get_issue_details, penify_hook.jira_client.JiraClient.update_issue_status.
List[str] penify_hook.jira_client.JiraClient.extract_issue_keys_from_branch(self, str branch_name)
Extracts JIRA issue keys from a branch name. This function searches through a given git branch name to find and return any JIRA issue keys that match the pattern. Common conventions for JIRA issue keys in branch names include: - feature/PROJECT-123-description - bugfix/PROJECT-123-fix-something - hotfix/PROJECT-123/short-desc Args: branch_name (str): The name of the git branch to search for JIRA issue keys. Returns: List[str]: A list of unique JIRA issue keys found in the branch name. Examples: extract_issue_keys_from_branch("feature/PROJ-456-add-new-feature") # Output: ['PROJ-456']
References penify_hook.jira_client.JiraClient.extract_issue_keys_from_branch, penify_hook.ui_utils.print_info.
Referenced by penify_hook.jira_client.JiraClient.extract_issue_keys_from_branch.
List[str] penify_hook.jira_client.JiraClient.extract_issue_keys(self, str text)
Extract JIRA issue keys from a given text. This function searches through the provided text to find and return all unique JIRA issue keys. A JIRA issue key typically follows the pattern of PROJECT-123, where PROJECT is alphanumeric and consists of at least one uppercase letter followed by one or more alphanumeric characters, and 123 is a numeric sequence. Args: text (str): The text in which to search for JIRA issue keys. Returns: List[str]: A list of unique JIRA issue keys found in the text.
Referenced by penify_hook.jira_client.JiraClient.format_commit_message_with_jira_info.
Optional[Dict[str, Any]] penify_hook.jira_client.JiraClient.get_issue_details(self, str issue_key)
Retrieve details of a JIRA issue based on its key. This function fetches detailed information about a specified JIRA issue using the provided issue key. It checks if the JIRA client is connected before attempting to retrieve the issue. If the client is not connected, it logs a warning and returns `None`. The function then attempts to fetch the issue from the JIRA server and constructs a dictionary containing various details about the issue such as its key, summary, status, description, assignee, reporter, type, priority, and URL. If any errors occur during this process, they are logged, and `None` is returned. Args: issue_key (str): The JIRA issue key (e.g., "PROJECT-123"). Returns: Dict[str, Any] or None: A dictionary containing the details of the JIRA issue if found, otherwise `None`.
References penify_hook.jira_client.JiraClient.is_connected, penify_hook.jira_client.JiraClient.jira_client.
Referenced by penify_hook.jira_client.JiraClient.format_commit_message_with_jira_info, penify_hook.jira_client.JiraClient.get_commit_context_from_issues.
bool penify_hook.jira_client.JiraClient.add_comment(self, str issue_key, str comment)
Add a comment to a JIRA issue. Args: issue_key (str): JIRA issue key (e.g., "PROJECT-123") comment (str): Comment text to add Returns: bool: True if the comment was added successfully, False otherwise
References penify_hook.jira_client.JiraClient.add_comment, penify_hook.jira_client.JiraClient.is_connected, penify_hook.jira_client.JiraClient.jira_client.
Referenced by penify_hook.jira_client.JiraClient.add_comment.
bool penify_hook.jira_client.JiraClient.update_issue_status(self, str issue_key, str transition_name)
Update the status of a JIRA issue. Args: issue_key (str): The key of the JIRA issue to be updated. transition_name (str): The name of the desired transition. Returns: bool: True if the status was successfully updated, False otherwise.
References penify_hook.jira_client.JiraClient.is_connected, penify_hook.jira_client.JiraClient.jira_client.
tuple penify_hook.jira_client.JiraClient.format_commit_message_with_jira_info(self, str commit_title, str commit_description, List[str] issue_keys=None)
Format commit message with JIRA issue information. Args: commit_title (str): The original commit title. commit_description (str): The original commit description. issue_keys (List[str]?): A list of JIRA issue keys to include in the commit message. If not provided, issue keys will be extracted from both the title and the description. Returns: tuple: A tuple containing the updated commit title and description with JIRA information included.
References penify_hook.jira_client.JiraClient.extract_issue_keys, penify_hook.jira_client.JiraClient.get_issue_details, penify_hook.jira_client.JiraClient.is_connected.
Referenced by penify_hook.jira_client.JiraClient.enhance_commit_message.
Dict[str, Any] penify_hook.jira_client.JiraClient.get_detailed_issue_context(self, str issue_key)
Retrieve comprehensive details about a JIRA issue including context for better commit messages. This function fetches detailed information from a specified JIRA issue and constructs a dictionary containing various context fields such as the issue summary, description, type, status, priority, comments, URL, and additional custom fields like acceptance criteria and sprint information. If any errors occur during the fetching process, appropriate warnings or errors are logged. Args: issue_key (str): The JIRA issue key (e.g., "PROJECT-123"). Returns: Dict[str, Any]: A dictionary containing business and technical context from the issue.
References penify_hook.jira_client.JiraClient.is_connected, penify_hook.jira_client.JiraClient.jira_client.
Referenced by penify_hook.jira_client.JiraClient.get_commit_context_from_issues.
Dict[str, Any] penify_hook.jira_client.JiraClient.get_commit_context_from_issues(self, List[str] issue_keys)
Gather contextual information from JIRA issues to improve commit messages. This function processes a list of JIRA issue keys, retrieves detailed context for each issue, and aggregates it into a dictionary that can be used to enhance commit messages. It first retrieves the primary issue (the first key in the list) and then gathers basic details for any related issues. The resulting context includes information from both the primary and related issues, along with all issue keys. Args: issue_keys: List of JIRA issue keys to gather information from Returns: Dict containing business and technical context from the issues
References penify_hook.jira_client.JiraClient.get_detailed_issue_context, penify_hook.jira_client.JiraClient.get_issue_details, penify_hook.jira_client.JiraClient.is_connected.
Referenced by penify_hook.jira_client.JiraClient.enhance_commit_message.
tuple penify_hook.jira_client.JiraClient.enhance_commit_message(self, str title, str description, List[str] issue_keys)
Enhance a commit message with business and technical context from JIRA issues. Args: title (str): Original commit title. description (str): Original commit description. issue_keys (List[str]): List of JIRA issue keys to include in the enhanced commit message. Returns: tuple: A tuple containing the enhanced commit title and description with added context from JIRA issues.
References penify_hook.jira_client.JiraClient.format_commit_message_with_jira_info, penify_hook.jira_client.JiraClient.get_commit_context_from_issues, penify_hook.jira_client.JiraClient.is_connected.