penify_hook::utils
penify_hook::utils.logger
def penify_hook.utils.get_repo_details(Repo repo)
Determine the details of a repository including its remote URL, hosting service, organization name, and repository name. This function extracts the remote URL from the given Git repository object and determines the hosting service (e.g., GitHub, Azure DevOps, Bitbucket, GitLab). It then parses the URL to extract the organization name and repository name. If the URL does not match any known hosting service pattern, it sets the hosting service as "Unknown". The function handles exceptions that may occur during this process and logs an error message if needed. Args: repo (Repo): A GitPython Repo object representing the local git repository. Returns: dict: A dictionary containing the organization name, repository name, and hosting service.
def penify_hook.utils.recursive_search_git_folder(folder_path)
Recursively searches for a .git folder starting from the given directory.
References penify_hook.utils.recursive_search_git_folder.
Referenced by penify_hook.commands.commit_commands.commit_code, penify_hook.commands.config_commands.get_penify_config, penify_hook.commands.config_commands.load_env_files, penify_hook.utils.recursive_search_git_folder, penify_hook.commands.auth_commands.save_credentials, penify_hook.commands.config_commands.save_jira_config, penify_hook.commands.config_commands.save_llm_config.
def penify_hook.utils.find_git_parent(path)
Traverse up from the given path to find the nearest directory containing a .git subdirectory.