penify_hook::commit_analyzer::CommitDocGenHook
penify_hook.commit_analyzer.CommitDocGenHook::llm_client
Referenced by penify_hook.commit_analyzer.CommitDocGenHook.get_summary.
def penify_hook.commit_analyzer.CommitDocGenHook.__init__(self, str repo_path, APIClient api_client, llm_client=None, jira_client=None)
References penify_hook.commit_analyzer.CommitDocGenHook.__init__.
Referenced by penify_hook.commit_analyzer.CommitDocGenHook.__init__.
dict penify_hook.commit_analyzer.CommitDocGenHook.get_summary(self, str instruction, bool generate_description)
Generate a summary for the commit based on the staged changes. This function retrieves the differences of the staged changes in the repository and generates a commit summary using the provided instruction. If there are no changes staged for commit, an exception is raised. If a JIRA client is connected, it will attempt to extract issue keys from the current branch and use them to fetch context. The summary can be generated either with a Language Model (LLM) client or through the API client. Args: instruction (str): A string containing instructions for generating the commit summary. generate_description (bool): Whether to include detailed descriptions in the summary. Returns: dict: The generated commit summary based on the staged changes, provided instruction, and any relevant JIRA context. The dictionary contains keys such as 'summary', 'description', etc., depending on whether a description was requested. Raises: ValueError: If there are no changes staged for commit.
References penify_hook.base_analyzer.BaseAnalyzer.api_client, penify_hook.jira_client.JiraClient.jira_client, penify_hook.commit_analyzer.CommitDocGenHook.llm_client, penify_hook.ui_utils.print_info, penify_hook.base_analyzer.BaseAnalyzer.repo, penify_hook.base_analyzer.BaseAnalyzer.repo_details.
Referenced by penify_hook.commit_analyzer.CommitDocGenHook.run.
def penify_hook.commit_analyzer.CommitDocGenHook.run(self, Optional[str] msg, bool edit_commit_message, bool generate_description)
Run the post-commit hook. This method processes the modified files from the last commit, stages them, and creates an auto-commit with an optional message. It also handles JIRA integration if available. If there is an error generating the commit summary, an exception is raised. Args: msg (Optional[str]): An optional message to include in the commit. edit_commit_message (bool): A flag indicating whether to open the git commit edit terminal after committing. generate_description (bool): A flag indicating whether to include a description in the commit message. Raises: Exception: If there is an error generating the commit summary.
References penify_hook.commit_analyzer.CommitDocGenHook._amend_commit, penify_hook.commit_analyzer.CommitDocGenHook.get_summary, penify_hook.jira_client.JiraClient.jira_client, penify_hook.ui_utils.print_info, penify_hook.ui_utils.print_success, penify_hook.commit_analyzer.CommitDocGenHook.process_jira_integration, penify_hook.base_analyzer.BaseAnalyzer.repo.
tuple penify_hook.commit_analyzer.CommitDocGenHook.process_jira_integration(self, str title, str description, str msg)
Process JIRA integration for the commit message. Args: title (str): Generated commit title. description (str): Generated commit description. msg (str): Original user message that might contain JIRA references. Returns: tuple: A tuple containing the updated commit title and description with included JIRA information.
References penify_hook.jira_client.JiraClient.jira_client, penify_hook.ui_utils.print_info, penify_hook.ui_utils.print_warning, penify_hook.base_analyzer.BaseAnalyzer.repo.
Referenced by penify_hook.commit_analyzer.CommitDocGenHook.run.
def penify_hook.commit_analyzer.CommitDocGenHook._amend_commit(self)
Open the default git editor for editing the commit message. This function changes the current working directory to the repository path, runs the git command to amend the last commit, and opens the default editor for the user to modify the commit message. After the operation, it returns to the original directory.
References penify_hook.base_analyzer.BaseAnalyzer.repo_path.
Referenced by penify_hook.commit_analyzer.CommitDocGenHook.run.