penify_hook::commands::commit_commands
def penify_hook.commands.commit_commands.commit_code(api_url, token, message, open_terminal, generate_description, llm_model=None, llm_api_base=None, llm_api_key=None, jira_url=None, jira_user=None, jira_api_token=None)
Enhance Git commits with AI-powered commit messages. This function allows for the generation of enhanced commit messages using natural language processing models and optionally integrates with JIRA for additional context. It processes the current Git folder to find relevant files and generates a detailed commit message based on the provided parameters. Args: api_url (str): URL of the API endpoint. token (str): Authentication token for the API. message (str): Initial commit message provided by the user. open_terminal (bool): Whether to open the terminal after committing. generate_description (bool): Whether to generate a detailed description in the commit message. llm_model (str?): The language model to use for generating the commit message. Defaults to None. llm_api_base (str?): Base URL of the LLM API. Defaults to None. llm_api_key (str?): API key for accessing the LLM service. Defaults to None. jira_url (str?): URL of the JIRA instance. Defaults to None. jira_user (str?): Username for authenticating with JIRA. Defaults to None. jira_api_token (str?): API token for accessing JIRA. Defaults to None.
References penify_hook.ui_utils.print_error, penify_hook.ui_utils.print_info, penify_hook.ui_utils.print_warning, penify_hook.utils.recursive_search_git_folder.
Referenced by penify_hook.commands.commit_commands.handle_commit, tests.test_commit_commands.TestCommitCommands.test_commit_code_error_handling, tests.test_commit_commands.TestCommitCommands.test_commit_code_with_jira_client, tests.test_commit_commands.TestCommitCommands.test_commit_code_with_jira_connection_failure, tests.test_commit_commands.TestCommitCommands.test_commit_code_with_llm_client.
def penify_hook.commands.commit_commands.setup_commit_parser(parser)
Generates a parser for setting up a command to generate smart commit messages. This function sets up an argument parser that can be used to generate commit messages with contextual information. It allows users to specify options such as including a message, opening an edit terminal before committing, and generating a detailed commit message. Args: parser (argparse.ArgumentParser): The ArgumentParser object to be configured.
Referenced by penify_hook.main.main, tests.test_commit_commands.TestCommitCommands.test_setup_commit_parser.
def penify_hook.commands.commit_commands.handle_commit(args)
Handle the commit functionality by processing arguments and invoking the appropriate commands. This function processes the provided command-line arguments to configure settings for commit operations, including LLM (Language Model) and Jira configurations. It then calls the `commit_code` function with these configurations to perform the actual commit operation. Args: args (argparse.Namespace): The parsed command-line arguments containing options like terminal, description, message, etc.
References penify_hook.commands.commit_commands.commit_code, penify_hook.commands.config_commands.get_jira_config, penify_hook.commands.config_commands.get_llm_config, penify_hook.commands.config_commands.get_token, penify_hook.ui_utils.print_info.
Referenced by penify_hook.main.main, tests.test_commit_commands.TestCommitCommands.test_handle_commit.