penify_hook::commands::doc_commands
string penify_hook::commands::doc_commands.docgen_description
def penify_hook.commands.doc_commands.generate_doc(api_url, token, location=None)
Generates documentation based on the given parameters. This function initializes an API client using the provided API URL and token. It then generates documentation by analyzing the specified location, which can be a folder, a file, or the current working directory if no location is provided. The function handles different types of analysis based on the input location and reports any errors encountered during the process. Args: api_url (str): The URL of the API to connect to for documentation generation. token (str): The authentication token for accessing the API. location (str?): The path to a specific file or folder to analyze. If not provided, the current working directory is used.
Referenced by penify_hook.commands.doc_commands.handle_docgen, tests.test_doc_commands.test_generate_doc_error_handling, tests.test_doc_commands.test_generate_doc_file_location, tests.test_doc_commands.test_generate_doc_folder_location, tests.test_doc_commands.test_generate_doc_no_location, tests.test_doc_commands.test_generate_doc_with_file_exception, tests.test_doc_commands.test_generate_doc_with_folder_exception.
def penify_hook.commands.doc_commands.setup_docgen_parser(parser)
Set up and configure a parser for documentation generation using Git commands. This function configures a parser with various subcommands and arguments necessary for generating documentation for Git diffs, files, or folders. It also installs and uninstalls commit hooks to automate documentation generation on commits. Args: parser (argparse.ArgumentParser): The parser to configure.
Referenced by penify_hook.main.main, tests.test_doc_commands.test_setup_docgen_parser.
def penify_hook.commands.doc_commands.handle_docgen(args)
Handle various subcommands related to document generation and hook management. This function processes different subcommands such as installing or uninstalling git hooks, and directly generating documentation based on provided arguments. Args: args (Namespace): Parsed command-line arguments containing the subcommand and location details.
References penify_hook.commands.doc_commands.generate_doc, penify_hook.commands.config_commands.get_token, penify_hook.commands.hook_commands.install_git_hook, penify_hook.commands.hook_commands.uninstall_git_hook.
Referenced by penify_hook.main.main, tests.test_doc_commands.test_handle_docgen_generate, tests.test_doc_commands.test_handle_docgen_install_hook, tests.test_doc_commands.test_handle_docgen_no_token, tests.test_doc_commands.test_handle_docgen_uninstall_hook.