penify_hook::commands::config_commands
bool penify_hook::commands::config_commands::DOTENV_AVAILABLE
penify_hook::commands::config_commands.path
None penify_hook.commands.config_commands.load_env_files()
Load environment variables from .env files in various locations, with proper priority (later files override earlier ones): 1. User home directory .env (lowest priority) 2. Git repo root directory .env (if in a git repo) 3. Current directory .env (highest priority) This function is called when the module is imported, ensuring env variables are available throughout the application lifecycle.
References penify_hook.commands.config_commands.load_env_files, penify_hook.utils.recursive_search_git_folder.
Referenced by penify_hook.commands.config_commands.get_jira_config, penify_hook.commands.config_commands.get_llm_config, penify_hook.commands.config_commands.get_token, penify_hook.commands.config_commands.load_env_files.
Path penify_hook.commands.config_commands.get_penify_config()
Get the home directory for the .penify configuration file. This function searches for the `.penify` file in the current directory and its parent directories until it finds it or reaches the home directory. If not found, it creates the `.penify` directory and an empty `config.json` file. Returns: Path: The path to the `config.json` file within the `.penify` directory.
References penify_hook.utils.recursive_search_git_folder.
Referenced by penify_hook.commands.config_commands.get_token, tests.test_config_commands.TestConfigCommands.test_get_penify_config_existing_dir, tests.test_config_commands.TestConfigCommands.test_get_penify_config_new_dir.
Any penify_hook.commands.config_commands.get_env_var_or_default(str env_var, Any default=None)
Get environment variable or return default value. Args: env_var: The environment variable name default: Default value if environment variable is not set Returns: Value of the environment variable or default
Referenced by penify_hook.commands.config_commands.get_jira_config, penify_hook.commands.config_commands.get_llm_config, penify_hook.commands.config_commands.get_token.
def penify_hook.commands.config_commands.save_llm_config(model, api_base, api_key)
Save LLM configuration settings to .env file. This function saves LLM configuration in the following priority: 1. Git repo root .env (if inside a git repo) 2. User home directory .env
References penify_hook.utils.recursive_search_git_folder.
Referenced by penify_hook.config_command.handle_config, tests.test_config_commands.TestConfigCommands.test_save_llm_config_failure, tests.test_config_commands.TestConfigCommands.test_save_llm_config_success.
def penify_hook.commands.config_commands.save_jira_config(url, username, api_token)
Save JIRA configuration settings to .env file. This function saves JIRA configuration in the following priority: 1. Git repo root .env (if inside a git repo) 2. User home directory .env
References penify_hook.utils.recursive_search_git_folder.
Referenced by penify_hook.commands.config_commands.config_jira_web, penify_hook.config_command.handle_config, tests.test_config_commands.TestConfigCommands.test_save_jira_config_success.
Dict[str, str] penify_hook.commands.config_commands.get_llm_config()
Get LLM configuration from environment variables. Environment variables: - PENIFY_LLM_MODEL: Model name - PENIFY_LLM_API_BASE: API base URL - PENIFY_LLM_API_KEY: API key Returns: dict: Configuration dictionary with model, api_base, and api_key
References penify_hook.commands.config_commands.get_env_var_or_default, penify_hook.commands.config_commands.load_env_files.
Referenced by penify_hook.commands.commit_commands.handle_commit, tests.test_config_commands.TestConfigCommands.test_get_llm_config_empty, tests.test_config_commands.TestConfigCommands.test_get_llm_config_exists, tests.test_config_commands.TestConfigCommands.test_get_llm_config_invalid_json.
Dict[str, str] penify_hook.commands.config_commands.get_jira_config()
Get JIRA configuration from environment variables. Environment variables: - PENIFY_JIRA_URL: JIRA URL - PENIFY_JIRA_USER: JIRA username - PENIFY_JIRA_TOKEN: JIRA API token Returns: dict: Configuration dictionary with url, username, and api_token
References penify_hook.commands.config_commands.get_env_var_or_default, penify_hook.commands.config_commands.load_env_files.
Referenced by penify_hook.commands.config_commands.config_jira_web, penify_hook.commands.commit_commands.handle_commit, tests.test_config_commands.TestConfigCommands.test_get_jira_config_exists.
def penify_hook.commands.config_commands.config_llm_web()
Open a web browser interface for configuring LLM settings. This function starts a temporary HTTP server that serves an HTML template for configuring Large Language Model (LLM) settings. It handles GET and POST requests to retrieve the current configuration, save new configurations, and suppress log messages. The server runs on a random port between 30000 and 50000, and it is accessible via a URL like http://localhost:<redirect_port>. The function opens this URL in the default web browser for configuration. Once configured, the server shuts down.
Referenced by penify_hook.config_command.handle_config, tests.test_web_config.TestWebConfig.test_config_llm_web_server_setup.
def penify_hook.commands.config_commands.config_jira_web()
Open a web browser interface for configuring JIRA settings. This function sets up a simple HTTP server using Python's built-in `http.server` module to handle GET and POST requests. The server serves an HTML page for configuration and handles saving the JIRA configuration details through API tokens and URLs. Upon successful configuration, it shuts down the server gracefully.
References penify_hook.commands.config_commands.get_jira_config, penify_hook.commands.config_commands.save_jira_config.
Referenced by penify_hook.config_command.handle_config, tests.test_web_config.TestWebConfig.test_config_jira_web_server_setup.
Optional[str] penify_hook.commands.config_commands.get_token()
Get the API token based on priority: 1. Environment variable PENIFY_API_TOKEN from any .env file 2. Config file 'api_keys' value Returns: str or None: API token if found, None otherwise
References penify_hook.commands.config_commands.get_env_var_or_default, penify_hook.commands.config_commands.get_penify_config, penify_hook.commands.config_commands.load_env_files.
Referenced by penify_hook.commands.commit_commands.handle_commit, penify_hook.commands.doc_commands.handle_docgen, tests.test_config_commands.TestConfigCommands.test_get_token_from_config, tests.test_config_commands.TestConfigCommands.test_get_token_from_env, tests.test_config_commands.TestConfigCommands.test_get_token_not_found.